name: dpvo
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - tensorboard
    - numba
    - tqdm
    - einops
    - pypose
    - kornia
    - plyfile
    - evo
    - opencv-python
    - yacs
